use serde::Deserialize;

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Modifier {
	Stiff,
	Salty,
	AoteStone,
	Waxed,
	Rooted,
	Candied,
	Perfect,
	Fleet,
	Fabled,
	Spiked,
	Hyper,
	Coldfusion,
	Blooming,
	Jaded,
	Jerry,
	Magnetic,
	Earthy,
	Fortified,
	Gilded,
	Cubic,
	Necrotic,
	Fruitful,
	Precise,
	Mossy,
	Pitchin,
	Undead,
	Mithraic,
	Reinforced,
	Ridiculous,
	Loving,
	Auspicious,
	Treacherous,
	Headstrong,
	Strengthened,
	Glistening,
	Bustling,
	Spiritual,
	Suspicious,
	Ambered,
	Blessed,
	Bulky,
	Submerged,
	Renowned,
	Giant,
	Bountiful,
	Chomp,
	Lucky,
	Stellar,
	Ancient,
	Refined,
	Empowered,
	Withered,
	Heated,
	Dirty,
	Moil,
	Toil,
	#[serde(other)]
	Other,
}

impl Modifier {
	#[must_use]
	#[inline]
	pub fn reforge_id(&self) -> Option<&'static str> {
		use Modifier::*;

		Some(match self {
			Stiff => "HARDENED_WOOD",
			Salty => "SALT_CUBE",
			AoteStone => "AOTE_STONE",
			Waxed => "BLAZE_WAX",
			Rooted => "BURROWING_SPORES",
			Candied => "CANDY_CORN",
			Perfect => "DIAMOND_ATOM",
			Fleet => "DIAMONITE",
			Fabled => "DRAGON_CLAW",
			Spiked => "DRAGON_SCALE",
			Hyper => "ENDSTONE_GEODE",
			Coldfusion => "ENTROPY_SUPPRESSOR",
			Blooming => "FLOWERING_BOUQUET",
			Jaded => "JADERALD",
			Jerry => "JERRY_STONE",
			Magnetic => "LAPIS_CRYSTAL",
			Earthy => "LARGE_WALNUT",
			Fortified => "METEOR_SHARD",
			Gilded => "MIDAS_JEWEL",
			Cubic => "MOLTEN_CUBE",
			Necrotic => "NECROMANCER_BROOCH",
			Fruitful => "ONYX",
			Precise => "OPTICAL_LENS",
			Mossy => "OVERGROWN_GRASS",
			Pitchin => "PITCHIN_KOI",
			Undead => "PREMIUM_FLESH",
			Mithraic => "PURE_MITHRIL",
			Reinforced => "RARE_DIAMOND",
			Ridiculous => "RED_NOSE",
			Loving => "RED_SCARF",
			Auspicious => "ROCK_GEMSTONE",
			Treacherous => "RUSTY_ANCHOR",
			Headstrong => "SALMON_OPAL",
			Strengthened => "SEARING_STONE",
			Glistening => "SHINY_PRISM",
			Bustling => "SKYMART_BROCHURE",
			Spiritual => "SPIRIT_DECOY",
			Suspicious => "SUSPICIOUS_VIAL",
			Ambered => "AMBER_MATERIAL",
			Blessed => "BLESSED_FRUIT",
			Bulky => "BULKY_STONE",
			Submerged => "DEEP_SEA_ORB",
			Renowned => "DRAGON_HORN",
			Giant => "GIANT_TOOTH",
			Bountiful => "GOLDEN_BALL",
			Chomp => "KUUDRA_MANDIBLE",
			Lucky => "LUCKY_DICE",
			Stellar => "PETRIFIED_STARFALL",
			Ancient => "PRECURSOR_GEAR",
			Refined => "REFINED_AMBER",
			Empowered => "SADAN_BROOCH",
			Withered => "WITHER_BLOOD",
			Heated => "HOT_STUFF",
			Dirty => "DIRT_BOTTLE",
			Moil => "MOIL_LOG",
			Toil => "TOIL_LOG",
			Other => return None,
		})
	}
}
